version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  node-app:
    build:
      context: ./server
    container_name: node-app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

volumes:
  mongo_data:
