version: '3.8'

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: listaDetarefas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
  pgadmin_data:
