apiVersion: v1
kind: Pod
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  containers:
  - name: goserver
    image: eduardodeveloper/hello-go:latest # Inclua a tag da imagem
    ports:
    - containerPort: 80 # Defina a porta que o contêiner usará
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
